def generate_plain_explanation(analysis_result):
    """
    Generates plain English explanation
    without any external API.
    Pure logic based on the results.
    """
    verdict = analysis_result.get("overall_verdict", "")
    score = analysis_result.get("overall_score", 0)
    modules = analysis_result.get("modules", {})
    inconsistencies = analysis_result.get("inconsistencies", [])

    # Collect high severity findings
    high_findings = []
    for module_name, module_data in modules.items():
        if not module_data or module_data.get("verdict") in [
            "SKIPPED", "ERROR", None
        ]:
            continue
        for ev in module_data.get("evidence", []):
            if ev.get("severity") == "high":
                high_findings.append({
                    "module": module_name,
                    "finding": ev["finding"]
                })

    is_fake = (
        "FAKE" in verdict or
        "MANIPULATED" in verdict or
        "SUSPICIOUS" in verdict
    )

    # Build explanation based on what was found
    if is_fake:
        if high_findings:
            main_finding = high_findings[0]["finding"]
            module = high_findings[0]["module"]

            if module == "text":
                if "fabricated" in main_finding.lower() or "cannot verify" in main_finding.lower():
                    explanation = (
                        f"This article contains names or people that do not exist "
                        f"in any verified database. "
                        f"When a news article mentions officials or experts that "
                        f"nobody can find — that is a strong sign the story was made up. "
                        f"Do not share this. Verify with a trusted news source first."
                    )
                elif "date" in main_finding.lower():
                    explanation = (
                        f"This article has a basic date error — "
                        f"the day of the week does not match the date given. "
                        f"Real journalists always check this. "
                        f"This mistake suggests the article was written carelessly "
                        f"or generated by a machine. "
                        f"Treat this with suspicion."
                    )
                elif "AI" in main_finding or "artificial" in main_finding.lower():
                    explanation = (
                        f"This text was most likely written by an AI like ChatGPT, "
                        f"not a human journalist. "
                        f"The writing is too uniform and predictable — "
                        f"every sentence follows the same pattern. "
                        f"AI-written content is not always false, "
                        f"but it requires extra verification."
                    )
                else:
                    explanation = (
                        f"This text shows {len(high_findings)} suspicious patterns. "
                        f"The content may contain false information. "
                        f"Please verify with trusted news sources before sharing."
                    )

            elif module == "image":
                if "metadata" in main_finding.lower():
                    explanation = (
                        f"This image has no camera information attached to it. "
                        f"Every real photo taken by a camera or phone automatically "
                        f"stores details like the camera model and time. "
                        f"This image has none of that — "
                        f"suggesting it was generated by AI or downloaded from somewhere else."
                    )
                elif "ela" in main_finding.lower() or "editing" in main_finding.lower():
                    explanation = (
                        f"This image shows signs of editing. "
                        f"Different parts of the image were saved at different "
                        f"quality levels — like puzzle pieces from different sources "
                        f"put together. "
                        f"Real unedited photos compress uniformly."
                    )
                else:
                    explanation = (
                        f"This image shows {len(high_findings)} signs of manipulation. "
                        f"Zoom into the face edges and hair boundary — "
                        f"look for unnatural smoothness or blurring. "
                        f"Do not trust this image without verifying the source."
                    )

            elif module == "audio":
                if "splice" in main_finding.lower():
                    explanation = (
                        f"This audio recording was stitched together from "
                        f"multiple separate recordings. "
                        f"You can hear this yourself — "
                        f"listen for the moment when the background sound "
                        f"suddenly changes. "
                        f"Someone edited this audio to make it say something "
                        f"it originally did not."
                    )
                elif "breath" in main_finding.lower():
                    explanation = (
                        f"This voice recording has an unnatural breathing pattern. "
                        f"The speaker goes a very long time without breathing — "
                        f"which is physically impossible for a real person. "
                        f"This is a strong sign the voice was generated by AI."
                    )
                else:
                    explanation = (
                        f"This audio shows signs of voice synthesis. "
                        f"The voice frequency patterns are unnaturally consistent — "
                        f"real human voices always vary naturally. "
                        f"This voice may have been cloned or generated by AI."
                    )

            elif module == "video":
                if "emotion" in main_finding.lower():
                    explanation = (
                        f"The person in this video shows unnatural facial expressions. "
                        f"Their face stays the same through the whole video "
                        f"even when saying emotional things. "
                        f"Real people's faces naturally match what they are saying. "
                        f"This frozen expression is a common sign of deepfake technology."
                    )
                elif "mismatch" in main_finding.lower():
                    explanation = (
                        f"The face and voice in this video do not match each other. "
                        f"The person is saying one thing emotionally "
                        f"but their face shows a completely different feeling. "
                        f"This is a strong sign the audio was replaced "
                        f"with someone else's voice."
                    )
                else:
                    explanation = (
                        f"This video shows signs of manipulation. "
                        f"Watch it slowly and focus on whether "
                        f"the lip movements match the spoken words. "
                        f"Also notice if the face expressions feel natural "
                        f"or robotic."
                    )
            else:
                explanation = (
                    f"Our system detected {len(high_findings)} suspicious signals "
                    f"in this content. "
                    f"The manipulation probability is {score}%. "
                    f"We recommend not sharing this content "
                    f"without verifying it from a trusted source."
                )

        elif inconsistencies:
            explanation = (
                f"Different parts of this content contradict each other. "
                f"{inconsistencies[0]['message']} "
                f"Genuine content is always consistent across all its parts. "
                f"This inconsistency is a strong sign of manipulation."
            )
        else:
            explanation = (
                f"This content shows suspicious patterns "
                f"with {score}% manipulation probability. "
                f"While we cannot pinpoint one specific reason, "
                f"multiple small signals suggest this may not be genuine. "
                f"Verify before sharing."
            )

    else:
        # Authentic content
        checked_modules = [
            name for name, data in modules.items()
            if data and data.get("verdict") not in ["SKIPPED", "ERROR", None]
        ]

        if len(checked_modules) > 1:
            modules_str = " and ".join(checked_modules)
            explanation = (
                f"This content appears to be authentic. "
                f"We checked the {modules_str} and found no signs "
                f"of manipulation or artificial generation. "
                f"The content passed all our forensic checks. "
                f"That said, always verify important news from "
                f"multiple trusted sources."
            )
        else:
            explanation = (
                f"This content appears to be genuine "
                f"({100 - score}% authenticity confidence). "
                f"No significant manipulation was detected. "
                f"Always verify important information "
                f"from multiple trusted sources."
            )

    return explanation